[build]
publish = "public"
command = "./stackbit-build.sh"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 404

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"

[[redirects]]
  from = "*.incode.com.au"
  to = "/index.html"
  status = 404
